#pragma once

#include <Common.h>

// The searchID is a number generated by wfc-server for each player, and used internally by
// the server to look up players. Sending it to the client is a convenient solution to
// the following problem:
// When Match packets are sent to the server, since the server's player map type
// key is the UDP address, and Match packets are sent over TCP, the server can't
// associate the sender with the player (checking for IP isn't a good option)
// Getting the wfcSearchId from the server and sending it in Match packets allows easy
// player lookup for the server. trade off is the security isn't great imo
typedef struct {
    char magic[8]; // "SEARCHID"
    u64 wfcSearchId;
} SearchIdPacket;
static_assert(sizeof(SearchIdPacket) == 16);
