#pragma once

#include <Common.h>

#include <revolution.h>

extern bool hasMKWServerAddress;
extern bool hasSentMKWServerAddressRequest;
extern SOSockAddrIn mkwServerAddr;

extern u64 wfcSearchId;

// The searchID is a number generated by wfc-server for each player, and used internally by
// the server to look up players. Sending it to the client is a convenient solution to
// the following problem:
// When Match packets are sent to the server, since the server's player map type
// key is the UDP address, and Match packets are sent over TCP, the server can't
// associate the sender with the player (checking for IP isn't a good option)
// Getting the wfcSearchId from the server and sending it in Match packets allows easy
// player lookup for the server. trade off is the security isn't great imo
typedef struct {
    char magic[8]; // "SEARCHID"
    u64 wfcSearchId;
} SearchIdPacket;
static_assert(sizeof(SearchIdPacket) == 16);

// different race packet types, currently we check the first byte (which should be reconsidered at
// some point) for the type of packet
typedef enum {
    MKW_SERVER_RACE_PACKET = 0xB,
    MKW_SERVER_ADDR_RESP = 0xC,
    MKW_SERVER_COMBINED_RACE_PACKET = 0xD,
} MKWServerPacketType;

// this enum's future is tbd, intent was to distinguish between
// different messages (other than race packets) sent by mkw-server (i.e, item decision responses)
typedef enum {
    MKW_SERVER_MSG_TYPE_SVR_ADDR = 0x1,
} MKWServerMessageType;

void tryGetMKWServerAddress();
void setMKWServerAddress(const u8 *msg, u32 len);
void resetMKWServerInfo();

void applyMKWServerHeader(u8 *packet, u8 aid);

bool trySendRACEPacketToMKWServer(const void *data, u32 size);

bool verifySearchIdMagic(const char *packet, u32 size);

bool handleSearchIdPacket(const u8 *packet, u32 size);

bool sendMessageToQR2(const u8 *data, u32 size);
